In [ ]:
import pandas as pd
from Modules.read_data import read_data
from Modules.handle_time import transform_time_and_duration
from Modules.handle_genres import explode_genres
from Questions.qone_taste_evolution import *

## **Variables**

In [ ]:
data_path_25 = '/Users/juanpazmino/Documents/Desarrollo/Personal_projects/SpotifyDataVis/data/2025/'
data_path_26 = '/Users/juanpazmino/Documents/Desarrollo/Personal_projects/SpotifyDataVis/data/2026/'

saved_tracks_25 = 'saved_tracks_20251018.csv'
track_details_25 = 'track_details_20251018.csv'

# Playlist

## **Lectura de los datos**

In [ ]:
df_saved_tracks_25 = read_data(data_path_25, saved_tracks_25)
df_track_details_25 = read_data(data_path_25, track_details_25)

In [ ]:
df_saved_tracks_25.head()

,track_id,track_name,artist_name,artist_id,album_name,album_id,release_date,duration_ms,popularity,added_at,explicit
0,2aAjWdZ7TsQYvyRUzAFXmB,Young Forever,Amelie Lens,5Ho1vKl1Uz8bJlk4vbmvmf,Young Forever,4BOWZWwm6WVWmco0HKt80s,2025-10-17,227091,0,2025-10-17T20:33:46Z,False
1,3G8AJXzCrwPCnHiQI1ENnm,Plumbum,1luu,6H7YXIE4ZT1Nxa2krwL6N4,Europium EP,0l22YC5T2pj3MvIxPMt9iT,2025-02-21,361414,9,2025-10-14T23:36:59Z,False
2,4VmcBQm0YzgK0MU5geXmNA,Godspeed,ADB,12YduHZJsgoAQlzLEDdT8T,Godspeed,0B3oIXhodX3Xb64ehNSAOn,2025-01-31,175889,10,2025-10-14T23:35:22Z,False
3,4wpX2rcuD8R6f9P78yzccy,Timelapse,TRYM,5Nd385K2g3s0828W8Ab70z,Timelapse,4ZbUxkHSXVHU499uVMjawk,2018-09-04,370285,27,2025-10-11T03:51:31Z,False
4,7pt0UDWnpiVJ1uEMP5iM0P,No Broke Boys - Lee Foss Remix,"Disco Lines, Tinashe, Lee Foss",5Kmr0b3ip8g9P2i0dLTC3Z,No Broke Boys (Lee Foss Remix),4pWH8vGb2ZmwdAdZqMqcJO,2025-10-03,209333,56,2025-10-03T21:24:49Z,True

In [ ]:
df_track_details_25.head()

,track_id,track_name,duration_ms,popularity,explicit,artist_genres
0,3LBWAYCXn4GCkg0jOgWD7D,Breathe In (Short Mix),247559,46,False,"melodic techno, melodic house, techno, progres..."
1,3G8AJXzCrwPCnHiQI1ENnm,Plumbum,361414,9,False,"hard techno, techno, acid techno"
2,4VmcBQm0YzgK0MU5geXmNA,Godspeed,175889,10,False,"hard house, eurodance, trance"
3,1rbJVNRXE8jASvaAzWw9s8,Diving with Whales - Daniel Portman Radio Mix,268292,27,False,"deep house, melodic house, progressive house, ..."
4,3HER2Njuttsq8Qs8sn2G1Y,On The Beat - Full Length Album Mix,357720,44,False,"post-disco, disco, funk"

In [ ]:
track_details_subset = df_track_details_25[['track_id', 'artist_genres']]
merged_list_details = pd.merge(df_saved_tracks_25, track_details_subset, on='track_id', how='left')

In [ ]:
merged_list_details.head()

,track_id,track_name,artist_name,artist_id,album_name,album_id,release_date,duration_ms,popularity,added_at,explicit,artist_genres
0,2aAjWdZ7TsQYvyRUzAFXmB,Young Forever,Amelie Lens,5Ho1vKl1Uz8bJlk4vbmvmf,Young Forever,4BOWZWwm6WVWmco0HKt80s,2025-10-17,227091,0,2025-10-17T20:33:46Z,False,"techno, acid techno, hard techno, tekno"
1,3G8AJXzCrwPCnHiQI1ENnm,Plumbum,1luu,6H7YXIE4ZT1Nxa2krwL6N4,Europium EP,0l22YC5T2pj3MvIxPMt9iT,2025-02-21,361414,9,2025-10-14T23:36:59Z,False,"hard techno, techno, acid techno"
2,4VmcBQm0YzgK0MU5geXmNA,Godspeed,ADB,12YduHZJsgoAQlzLEDdT8T,Godspeed,0B3oIXhodX3Xb64ehNSAOn,2025-01-31,175889,10,2025-10-14T23:35:22Z,False,"hard house, eurodance, trance"
3,4wpX2rcuD8R6f9P78yzccy,Timelapse,TRYM,5Nd385K2g3s0828W8Ab70z,Timelapse,4ZbUxkHSXVHU499uVMjawk,2018-09-04,370285,27,2025-10-11T03:51:31Z,False,"hard techno, techno, acid techno, tekno"
4,7pt0UDWnpiVJ1uEMP5iM0P,No Broke Boys - Lee Foss Remix,"Disco Lines, Tinashe, Lee Foss",5Kmr0b3ip8g9P2i0dLTC3Z,No Broke Boys (Lee Foss Remix),4pWH8vGb2ZmwdAdZqMqcJO,2025-10-03,209333,56,2025-10-03T21:24:49Z,True,"stutter house, alternative r&b, tech house, house"

In [ ]:
df_clean_track_list = transform_time_and_duration(merged_list_details)
df_clean_track_list.head()

,track_id,track_name,artist_name,artist_id,album_name,album_id,release_date,popularity,added_at,explicit,artist_genres,added_year,added_month,duration_mins
0,2aAjWdZ7TsQYvyRUzAFXmB,Young Forever,Amelie Lens,5Ho1vKl1Uz8bJlk4vbmvmf,Young Forever,4BOWZWwm6WVWmco0HKt80s,2025-10-17,0,2025-10-17 20:33:46+00:00,False,"techno, acid techno, hard techno, tekno",2025,10,3.784850
1,3G8AJXzCrwPCnHiQI1ENnm,Plumbum,1luu,6H7YXIE4ZT1Nxa2krwL6N4,Europium EP,0l22YC5T2pj3MvIxPMt9iT,2025-02-21,9,2025-10-14 23:36:59+00:00,False,"hard techno, techno, acid techno",2025,10,6.023567
2,4VmcBQm0YzgK0MU5geXmNA,Godspeed,ADB,12YduHZJsgoAQlzLEDdT8T,Godspeed,0B3oIXhodX3Xb64ehNSAOn,2025-01-31,10,2025-10-14 23:35:22+00:00,False,"hard house, eurodance, trance",2025,10,2.931483
3,4wpX2rcuD8R6f9P78yzccy,Timelapse,TRYM,5Nd385K2g3s0828W8Ab70z,Timelapse,4ZbUxkHSXVHU499uVMjawk,2018-09-04,27,2025-10-11 03:51:31+00:00,False,"hard techno, techno, acid techno, tekno",2025,10,6.171417
4,7pt0UDWnpiVJ1uEMP5iM0P,No Broke Boys - Lee Foss Remix,"Disco Lines, Tinashe, Lee Foss",5Kmr0b3ip8g9P2i0dLTC3Z,No Broke Boys (Lee Foss Remix),4pWH8vGb2ZmwdAdZqMqcJO,2025-10-03,56,2025-10-03 21:24:49+00:00,True,"stutter house, alternative r&b, tech house, house",2025,10,3.488883

In [ ]:
df_exploded_track_list = explode_genres(df_clean_track_list)
df_exploded_track_list.head()

,track_id,track_name,artist_name,artist_id,album_name,album_id,release_date,popularity,added_at,explicit,artist_genres,added_year,added_month,duration_mins,genre_list
0,2aAjWdZ7TsQYvyRUzAFXmB,Young Forever,Amelie Lens,5Ho1vKl1Uz8bJlk4vbmvmf,Young Forever,4BOWZWwm6WVWmco0HKt80s,2025-10-17,0,2025-10-17 20:33:46+00:00,False,"techno, acid techno, hard techno, tekno",2025,10,3.784850,techno
0,2aAjWdZ7TsQYvyRUzAFXmB,Young Forever,Amelie Lens,5Ho1vKl1Uz8bJlk4vbmvmf,Young Forever,4BOWZWwm6WVWmco0HKt80s,2025-10-17,0,2025-10-17 20:33:46+00:00,False,"techno, acid techno, hard techno, tekno",2025,10,3.784850,acid techno
0,2aAjWdZ7TsQYvyRUzAFXmB,Young Forever,Amelie Lens,5Ho1vKl1Uz8bJlk4vbmvmf,Young Forever,4BOWZWwm6WVWmco0HKt80s,2025-10-17,0,2025-10-17 20:33:46+00:00,False,"techno, acid techno, hard techno, tekno",2025,10,3.784850,hard techno
0,2aAjWdZ7TsQYvyRUzAFXmB,Young Forever,Amelie Lens,5Ho1vKl1Uz8bJlk4vbmvmf,Young Forever,4BOWZWwm6WVWmco0HKt80s,2025-10-17,0,2025-10-17 20:33:46+00:00,False,"techno, acid techno, hard techno, tekno",2025,10,3.784850,tekno
1,3G8AJXzCrwPCnHiQI1ENnm,Plumbum,1luu,6H7YXIE4ZT1Nxa2krwL6N4,Europium EP,0l22YC5T2pj3MvIxPMt9iT,2025-02-21,9,2025-10-14 23:36:59+00:00,False,"hard techno, techno, acid techno",2025,10,6.023567,hard techno

***
## **Procesamiento de datos**

In [ ]:
top_genres = get_top_genres(df_exploded_track_list)
top_genres.head()

NameError: name 'get_top_genres' is not defined