In [1]:
import pandas as pd
import altair as alt

In [2]:
data_path_25 = '/Users/juanpazmino/Documents/Desarrollo/Personal_projects/SpotifyDataVis/data/2025/'
data_path_26 = '/Users/juanpazmino/Documents/Desarrollo/Personal_projects/SpotifyDataVis/data/2026/'

In [3]:
df_saved_tracks_26 = pd.read_csv(f'{data_path_26}saved_tracks_20260315.csv')
df_saved_tracks_26['added_at'] = pd.to_datetime(df_saved_tracks_26['added_at'])
df_saved_tracks_26.info()

<class 'pandas.DataFrame'>
RangeIndex: 2955 entries, 0 to 2954
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   track_id      2955 non-null   str
 1   track_name    2954 non-null   str
 2   artist_name   2954 non-null   str
 3   artist_id     2955 non-null   str
 4   album_name    2954 non-null   str
 5   album_id      2955 non-null   str
 6   release_date  2955 non-null   str
 7   duration_ms   2955 non-null   int64
 8   popularity    2955 non-null   int64
 9   added_at      2955 non-null   datetime64[us, UTC]
 10  explicit      2955 non-null   bool
dtypes: bool(1), datetime64[us, UTC](1), int64(2), str(7)
memory usage: 233.9 KB

In [4]:
df_saved_tracks_26.head()

,track_id,track_name,artist_name,artist_id,album_name,album_id,release_date,duration_ms,popularity,added_at,explicit
0,2eiITzUVZ1ErRTpoVpsoHQ,Katharsis,GLOWING TRAUMA,4iNpAnWsXj1BQIcQmfm2N7,This Curse Is a Blessing,59VsrPnYnZf2lvbPH3UoMs,2024-08-23,277080,11,2026-03-09 20:35:35+00:00,False
1,1jy7SkRcmBCTcv4ZMtwz29,Loud Places,"Jamie xx, Romy",7A0awCXkE1FtSU8B0qwOJQ,In Colour,4gaNWHu5Caj3ItkYZ5i6uh,2015-06-01,283066,60,2026-03-08 13:48:27+00:00,False
2,6LUfuyLgvgqrykiTE6sJHY,Stylo (feat. Mos Def and Bobby Womack),"Gorillaz, Bobby Womack, Mos Def",3AA28KZvwAUcZuOKwyblJQ,Plastic Beach,2dIGnmEIy1WZIcZCFSj6i8,2010-03-03,270520,66,2026-03-02 15:40:51+00:00,False
3,1foMv2HQwfQ2vntFf9HFeG,Rhinestone Eyes,Gorillaz,3AA28KZvwAUcZuOKwyblJQ,Plastic Beach,2dIGnmEIy1WZIcZCFSj6i8,2010-03-03,200173,79,2026-03-02 15:36:14+00:00,False
4,0YHqyIiqJ6QoKKLMDkbcbL,One Percent,Gorillaz,3AA28KZvwAUcZuOKwyblJQ,The Now Now,1amYhlukNF8WdaQC3gKkgL,2018-06-29,141360,49,2026-03-02 02:48:31+00:00,False

In [5]:
from datetime import datetime
target_time = datetime.fromisoformat('2026-03-02T15:36:14+00:00')
matching_rows = df_saved_tracks_26.loc[df_saved_tracks_26['added_at'] == target_time]
matching_rows

,track_id,track_name,artist_name,artist_id,album_name,album_id,release_date,duration_ms,popularity,added_at,explicit
3,1foMv2HQwfQ2vntFf9HFeG,Rhinestone Eyes,Gorillaz,3AA28KZvwAUcZuOKwyblJQ,Plastic Beach,2dIGnmEIy1WZIcZCFSj6i8,2010-03-03,200173,79,2026-03-02 15:36:14+00:00,False

In [6]:
start_date = datetime.fromisoformat('2025-10-17T20:33:46+00:00')
filtered_df_saved_tracks_26 = df_saved_tracks_26.loc[(df_saved_tracks_26['added_at'] >= start_date)]
filtered_df_saved_tracks_26

,track_id,track_name,artist_name,artist_id,album_name,album_id,release_date,duration_ms,popularity,added_at,explicit
0,2eiITzUVZ1ErRTpoVpsoHQ,Katharsis,GLOWING TRAUMA,4iNpAnWsXj1BQIcQmfm2N7,This Curse Is a Blessing,59VsrPnYnZf2lvbPH3UoMs,2024-08-23,277080,11,2026-03-09 20:35:35+00:00,False
1,1jy7SkRcmBCTcv4ZMtwz29,Loud Places,"Jamie xx, Romy",7A0awCXkE1FtSU8B0qwOJQ,In Colour,4gaNWHu5Caj3ItkYZ5i6uh,2015-06-01,283066,60,2026-03-08 13:48:27+00:00,False
2,6LUfuyLgvgqrykiTE6sJHY,Stylo (feat. Mos Def and Bobby Womack),"Gorillaz, Bobby Womack, Mos Def",3AA28KZvwAUcZuOKwyblJQ,Plastic Beach,2dIGnmEIy1WZIcZCFSj6i8,2010-03-03,270520,66,2026-03-02 15:40:51+00:00,False
3,1foMv2HQwfQ2vntFf9HFeG,Rhinestone Eyes,Gorillaz,3AA28KZvwAUcZuOKwyblJQ,Plastic Beach,2dIGnmEIy1WZIcZCFSj6i8,2010-03-03,200173,79,2026-03-02 15:36:14+00:00,False
4,0YHqyIiqJ6QoKKLMDkbcbL,One Percent,Gorillaz,3AA28KZvwAUcZuOKwyblJQ,The Now Now,1amYhlukNF8WdaQC3gKkgL,2018-06-29,141360,49,2026-03-02 02:48:31+00:00,False
...,...,...,...,...,...,...,...,...,...,...,...
86,4xvUoI9q9QWIzExBXhdWNc,Not Built to Be Lost,"Tham, Retarded Sick",609hP92W6p3l5agWsi1pnb,Love Is Not Enough,1jDyMsF4AbobdN3gRVFRx4,2025-10-24,288000,27,2025-10-29 02:35:09+00:00,False
87,3IqN0qrcsgWIAWKowc0qlb,Я твой враг,t.A.T.u.,2Q3eZMfDQgT8MhPowKFXYO,200 По встречной,1Sh5wXsKdvWxovnLp57jXw,2002-01-01,255058,22,2025-10-27 02:53:24+00:00,False
88,41b580HIhl087op0j5jrAE,Endless Game,KAS:ST,7orlzf5LTqSnCzURkZFebN,ADORE,4OXG77xxFnu04FxGuMZwyy,2025-10-24,181241,26,2025-10-25 12:40:05+00:00,False
89,55mBen1aWkKJC9W3Mzjo5J,BR3ATH3,Kobosil,2ZvIFwl0BuQgHqWvDE80hC,BR3ATH3,4IjgjKh1QcQyx1K7xr2MKR,2025-10-15,289000,58,2025-10-18 03:35:43+00:00,False
90,2aAjWdZ7TsQYvyRUzAFXmB,Young Forever,Amelie Lens,5Ho1vKl1Uz8bJlk4vbmvmf,Young Forever,4BOWZWwm6WVWmco0HKt80s,2025-10-17,227091,57,2025-10-17 20:33:46+00:00,False

In [7]:
filtered_df_saved_tracks_26['track_id']

0     2eiITzUVZ1ErRTpoVpsoHQ
1     1jy7SkRcmBCTcv4ZMtwz29
2     6LUfuyLgvgqrykiTE6sJHY
3     1foMv2HQwfQ2vntFf9HFeG
4     0YHqyIiqJ6QoKKLMDkbcbL
               ...
86    4xvUoI9q9QWIzExBXhdWNc
87    3IqN0qrcsgWIAWKowc0qlb
88    41b580HIhl087op0j5jrAE
89    55mBen1aWkKJC9W3Mzjo5J
90    2aAjWdZ7TsQYvyRUzAFXmB
Name: track_id, Length: 91, dtype: str